create table Addresses (
  id int generated by default as identity not null constraint Addresses_PK primary key,
  street varchar(255) not null,
  city varchar(100) not null,
  province varchar(100) not null,
  postalCode varchar(10) not null,
  country varchar(255) not null
);