drop table Transactions;

create table Transactions (
  id int generated by default as identity not null constraint Transactions_PK primary key,
  -- Foreign Key Users.zipPayId
  payorId varchar(12) not null constraint Transactions_CK_payorId references Users(zipPayId),
  payeeId varchar(12) not null constraint Transactions_CK_payeeId references Users(zipPayId), 
  amount decimal(5, 2) not null,
  txDate timestamp not null default current timestamp,
  txType varchar(20) not null default 'payment' constraint Transactions_CK_txType check (txType in ('payment', 'charge')),
  txStatus varchar(20) not null default 'open' constraint Transactions_CK_txStatus check (txStatus in ('open', 'settled')),
  reason varchar(2048),
  visibility varchar(20) not null default 'public' constraint Transactions_CK_visibility check (visibility in ('public', 'private')),
  txVersion int default 1,
  active boolean not null default true,
  -- always be the update time of the last record
  lastUpdated timestamp not null default current timestamp
);
