drop table Users;

create table Users (
  id int generated by default as identity not null constraint Users_PK primary key,
  userVersion int default 1,
  active boolean not null default true,
  -- always be the update time of the last record
  lastUpdated timestamp not null default current timestamp,
  displayName varchar(255) not null,
  -- TODO: build a string as substr(id, 0, 4) + '$' + hexString (4 chars)
  zipPayId varchar(12) not null constraint Users_CK_zipPayId unique,
  email varchar(50) not null,
  street varchar(255) not null,
  city varchar(100) not null,
  province varchar(100) not null,
  postalCode varchar(10) not null,
  country varchar(255) not null,
  largeAvatar varchar(255),
  mediumAvatar varchar(255),
  thumbnailAvatar varchar(255),
  -- 'person' or 'corporation'
  userType varchar(20) not null default 'person' constraint Users_CK_userType check (userType in ('person', 'corporate'))
);